/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAuth: typeof import('./../components/AppAuth/index.vue')['default']
    AppNotAllowed: typeof import('./../components/AppNotAllowed/index.vue')['default']
    AppPageLayout: typeof import('./../components/AppPageLayout/index.vue')['default']
    AppSetting: typeof import('./../components/AppSetting/index.vue')['default']
    KmAvatar: typeof import('@kpu-mobile/components')['KmAvatar']
    KmBadge: typeof import('@kpu-mobile/components')['KmBadge']
    KmButton: typeof import('@kpu-mobile/components')['KmButton']
    KmButtonGroup: typeof import('@kpu-mobile/components')['KmButtonGroup']
    KmCard: typeof import('@kpu-mobile/components')['KmCard']
    KmCheckbox: typeof import('@kpu-mobile/components')['KmCheckbox']
    KmDivider: typeof import('@kpu-mobile/components')['KmDivider']
    KmDrawer: typeof import('@kpu-mobile/components')['KmDrawer']
    KmIcon: typeof import('@kpu-mobile/components')['KmIcon']
    KmInput: typeof import('@kpu-mobile/components')['KmInput']
    KmLoading: typeof import('@kpu-mobile/components')['KmLoading']
    KmModal: typeof import('@kpu-mobile/components')['KmModal']
    KmPageMain: typeof import('@kpu-mobile/components')['KmPageMain']
    KmScrollArea: typeof import('@kpu-mobile/components')['KmScrollArea']
    KmSelect: typeof import('@kpu-mobile/components')['KmSelect']
    KmSlider: typeof import('@kpu-mobile/components')['KmSlider']
    KmSwitch: typeof import('@kpu-mobile/components')['KmSwitch']
    KmTabs: typeof import('@kpu-mobile/components')['KmTabs']
    KmToast: typeof import('@kpu-mobile/components')['KmToast']
    KmTrend: typeof import('@kpu-mobile/components')['KmTrend']
  }
}

// For TSX support
declare global {
  const AppAuth: typeof import('./../components/AppAuth/index.vue')['default']
  const AppNotAllowed: typeof import('./../components/AppNotAllowed/index.vue')['default']
  const AppPageLayout: typeof import('./../components/AppPageLayout/index.vue')['default']
  const AppSetting: typeof import('./../components/AppSetting/index.vue')['default']
  const KmAvatar: typeof import('@kpu-mobile/components')['KmAvatar']
  const KmBadge: typeof import('@kpu-mobile/components')['KmBadge']
  const KmButton: typeof import('@kpu-mobile/components')['KmButton']
  const KmButtonGroup: typeof import('@kpu-mobile/components')['KmButtonGroup']
  const KmCard: typeof import('@kpu-mobile/components')['KmCard']
  const KmCheckbox: typeof import('@kpu-mobile/components')['KmCheckbox']
  const KmDivider: typeof import('@kpu-mobile/components')['KmDivider']
  const KmDrawer: typeof import('@kpu-mobile/components')['KmDrawer']
  const KmIcon: typeof import('@kpu-mobile/components')['KmIcon']
  const KmInput: typeof import('@kpu-mobile/components')['KmInput']
  const KmLoading: typeof import('@kpu-mobile/components')['KmLoading']
  const KmModal: typeof import('@kpu-mobile/components')['KmModal']
  const KmPageMain: typeof import('@kpu-mobile/components')['KmPageMain']
  const KmScrollArea: typeof import('@kpu-mobile/components')['KmScrollArea']
  const KmSelect: typeof import('@kpu-mobile/components')['KmSelect']
  const KmSlider: typeof import('@kpu-mobile/components')['KmSlider']
  const KmSwitch: typeof import('@kpu-mobile/components')['KmSwitch']
  const KmTabs: typeof import('@kpu-mobile/components')['KmTabs']
  const KmToast: typeof import('@kpu-mobile/components')['KmToast']
  const KmTrend: typeof import('@kpu-mobile/components')['KmTrend']
}
