/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KmAnimatedCountTo: typeof import('./../ui/components/KmAnimatedCountTo/index.vue')['default']
    KmAnimatedCountToGroup: typeof import('./../ui/components/KmAnimatedCountToGroup/index.vue')['default']
    KmAppSetting: typeof import('./../ui/components/KmAppSetting/index.vue')['default']
    KmAuth: typeof import('./../ui/components/KmAuth/index.vue')['default']
    KmAvatar: typeof import('./../ui/components/KmAvatar/index.vue')['default']
    KmBadge: typeof import('./../ui/components/KmBadge/index.vue')['default']
    KmButton: typeof import('./../ui/components/KmButton/index.vue')['default']
    KmCard: typeof import('./../ui/components/KmCard/index.vue')['default']
    KmCheckbox: typeof import('./../ui/components/KmCheckbox/index.vue')['default']
    KmCode: typeof import('./../ui/components/KmCode/index.vue')['default']
    KmCodePreview: typeof import('./../ui/components/KmCodePreview/index.vue')['default']
    KmCountTo: typeof import('./../ui/components/KmCountTo/index.vue')['default']
    KmDigitalCard: typeof import('./../ui/components/KmDigitalCard/index.vue')['default']
    KmDivider: typeof import('./../ui/components/KmDivider/index.vue')['default']
    KmDrawer: typeof import('./../ui/components/KmDrawer/index.vue')['default']
    KmIcon: typeof import('./../ui/components/KmIcon/index.vue')['default']
    KmInput: typeof import('./../ui/components/KmInput/index.vue')['default']
    KmLoading: typeof import('./../ui/components/KmLoading/index.vue')['default']
    KmMarquee: typeof import('./../ui/components/KmMarquee/index.vue')['default']
    KmModal: typeof import('./../ui/components/KmModal/index.vue')['default']
    KmMultiStepLoader: typeof import('./../ui/components/KmMultiStepLoader/index.vue')['default']
    KmNotAllowed: typeof import('./../ui/components/KmNotAllowed/index.vue')['default']
    KmPageLayout: typeof import('./../ui/components/KmPageLayout/index.vue')['default']
    KmPageMain: typeof import('./../ui/components/KmPageMain/index.vue')['default']
    KmParticlesBg: typeof import('./../ui/components/KmParticlesBg/index.vue')['default']
    KmPatternBg: typeof import('./../ui/components/KmPatternBg/index.vue')['default']
    KmScratchOff: typeof import('./../ui/components/KmScratchOff/index.vue')['default']
    KmScrollArea: typeof import('./../ui/components/KmScrollArea/index.vue')['default']
    KmSelect: typeof import('./../ui/components/KmSelect/index.vue')['default']
    KmSlider: typeof import('./../ui/components/KmSlider/index.vue')['default']
    KmSparkline: typeof import('./../ui/components/KmSparkline/index.vue')['default']
    KmSpringDrawer: typeof import('./../ui/components/KmSpringDrawer/index.vue')['default']
    KmSwitch: typeof import('./../ui/components/KmSwitch/index.vue')['default']
    KmTabs: typeof import('./../ui/components/KmTabs/index.vue')['default']
    KmTimeline: typeof import('./../ui/components/KmTimeline/index.vue')['default']
    KmToast: typeof import('./../ui/components/KmToast/index.vue')['default']
    KmTrend: typeof import('./../ui/components/KmTrend/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanFieldCalendar: typeof import('./../components/VanFieldCalendar/index.vue')['default']
    VanFieldDatePicker: typeof import('./../components/VanFieldDatePicker/index.vue')['default']
    VanFieldPicker: typeof import('./../components/VanFieldPicker/index.vue')['default']
  }
}

// For TSX support
declare global {
  const KmAnimatedCountTo: typeof import('./../ui/components/KmAnimatedCountTo/index.vue')['default']
  const KmAnimatedCountToGroup: typeof import('./../ui/components/KmAnimatedCountToGroup/index.vue')['default']
  const KmAppSetting: typeof import('./../ui/components/KmAppSetting/index.vue')['default']
  const KmAuth: typeof import('./../ui/components/KmAuth/index.vue')['default']
  const KmAvatar: typeof import('./../ui/components/KmAvatar/index.vue')['default']
  const KmBadge: typeof import('./../ui/components/KmBadge/index.vue')['default']
  const KmButton: typeof import('./../ui/components/KmButton/index.vue')['default']
  const KmCard: typeof import('./../ui/components/KmCard/index.vue')['default']
  const KmCheckbox: typeof import('./../ui/components/KmCheckbox/index.vue')['default']
  const KmCode: typeof import('./../ui/components/KmCode/index.vue')['default']
  const KmCodePreview: typeof import('./../ui/components/KmCodePreview/index.vue')['default']
  const KmCountTo: typeof import('./../ui/components/KmCountTo/index.vue')['default']
  const KmDigitalCard: typeof import('./../ui/components/KmDigitalCard/index.vue')['default']
  const KmDivider: typeof import('./../ui/components/KmDivider/index.vue')['default']
  const KmDrawer: typeof import('./../ui/components/KmDrawer/index.vue')['default']
  const KmIcon: typeof import('./../ui/components/KmIcon/index.vue')['default']
  const KmInput: typeof import('./../ui/components/KmInput/index.vue')['default']
  const KmLoading: typeof import('./../ui/components/KmLoading/index.vue')['default']
  const KmMarquee: typeof import('./../ui/components/KmMarquee/index.vue')['default']
  const KmModal: typeof import('./../ui/components/KmModal/index.vue')['default']
  const KmMultiStepLoader: typeof import('./../ui/components/KmMultiStepLoader/index.vue')['default']
  const KmNotAllowed: typeof import('./../ui/components/KmNotAllowed/index.vue')['default']
  const KmPageLayout: typeof import('./../ui/components/KmPageLayout/index.vue')['default']
  const KmPageMain: typeof import('./../ui/components/KmPageMain/index.vue')['default']
  const KmParticlesBg: typeof import('./../ui/components/KmParticlesBg/index.vue')['default']
  const KmPatternBg: typeof import('./../ui/components/KmPatternBg/index.vue')['default']
  const KmScratchOff: typeof import('./../ui/components/KmScratchOff/index.vue')['default']
  const KmScrollArea: typeof import('./../ui/components/KmScrollArea/index.vue')['default']
  const KmSelect: typeof import('./../ui/components/KmSelect/index.vue')['default']
  const KmSlider: typeof import('./../ui/components/KmSlider/index.vue')['default']
  const KmSparkline: typeof import('./../ui/components/KmSparkline/index.vue')['default']
  const KmSpringDrawer: typeof import('./../ui/components/KmSpringDrawer/index.vue')['default']
  const KmSwitch: typeof import('./../ui/components/KmSwitch/index.vue')['default']
  const KmTabs: typeof import('./../ui/components/KmTabs/index.vue')['default']
  const KmTimeline: typeof import('./../ui/components/KmTimeline/index.vue')['default']
  const KmToast: typeof import('./../ui/components/KmToast/index.vue')['default']
  const KmTrend: typeof import('./../ui/components/KmTrend/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const VanFieldCalendar: typeof import('./../components/VanFieldCalendar/index.vue')['default']
  const VanFieldDatePicker: typeof import('./../components/VanFieldDatePicker/index.vue')['default']
  const VanFieldPicker: typeof import('./../components/VanFieldPicker/index.vue')['default']
}