/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/feature/': RouteRecordInfo<
      '/feature/',
      '/feature',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/basic': RouteRecordInfo<
      '/feature/component/basic',
      '/feature/component/basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/animated_count_to/': RouteRecordInfo<
      '/feature/component/built_in/animated_count_to/',
      '/feature/component/built_in/animated_count_to',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/avatar/': RouteRecordInfo<
      '/feature/component/built_in/avatar/',
      '/feature/component/built_in/avatar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/badge/': RouteRecordInfo<
      '/feature/component/built_in/badge/',
      '/feature/component/built_in/badge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/button/': RouteRecordInfo<
      '/feature/component/built_in/button/',
      '/feature/component/built_in/button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/card/': RouteRecordInfo<
      '/feature/component/built_in/card/',
      '/feature/component/built_in/card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/checkbox/': RouteRecordInfo<
      '/feature/component/built_in/checkbox/',
      '/feature/component/built_in/checkbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/count_to/': RouteRecordInfo<
      '/feature/component/built_in/count_to/',
      '/feature/component/built_in/count_to',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/digital_card/': RouteRecordInfo<
      '/feature/component/built_in/digital_card/',
      '/feature/component/built_in/digital_card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/divider/': RouteRecordInfo<
      '/feature/component/built_in/divider/',
      '/feature/component/built_in/divider',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/drawer/': RouteRecordInfo<
      '/feature/component/built_in/drawer/',
      '/feature/component/built_in/drawer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/input/': RouteRecordInfo<
      '/feature/component/built_in/input/',
      '/feature/component/built_in/input',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/loading/': RouteRecordInfo<
      '/feature/component/built_in/loading/',
      '/feature/component/built_in/loading',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/marquee/': RouteRecordInfo<
      '/feature/component/built_in/marquee/',
      '/feature/component/built_in/marquee',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/modal/': RouteRecordInfo<
      '/feature/component/built_in/modal/',
      '/feature/component/built_in/modal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/multi_step_loader/': RouteRecordInfo<
      '/feature/component/built_in/multi_step_loader/',
      '/feature/component/built_in/multi_step_loader',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/page_main/': RouteRecordInfo<
      '/feature/component/built_in/page_main/',
      '/feature/component/built_in/page_main',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/particles_bg/': RouteRecordInfo<
      '/feature/component/built_in/particles_bg/',
      '/feature/component/built_in/particles_bg',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/pattern_bg/': RouteRecordInfo<
      '/feature/component/built_in/pattern_bg/',
      '/feature/component/built_in/pattern_bg',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/scratch_off/': RouteRecordInfo<
      '/feature/component/built_in/scratch_off/',
      '/feature/component/built_in/scratch_off',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/scroll_area/': RouteRecordInfo<
      '/feature/component/built_in/scroll_area/',
      '/feature/component/built_in/scroll_area',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/select/': RouteRecordInfo<
      '/feature/component/built_in/select/',
      '/feature/component/built_in/select',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/slider/': RouteRecordInfo<
      '/feature/component/built_in/slider/',
      '/feature/component/built_in/slider',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/sparkline/': RouteRecordInfo<
      '/feature/component/built_in/sparkline/',
      '/feature/component/built_in/sparkline',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/spring_drawer/': RouteRecordInfo<
      '/feature/component/built_in/spring_drawer/',
      '/feature/component/built_in/spring_drawer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/switch/': RouteRecordInfo<
      '/feature/component/built_in/switch/',
      '/feature/component/built_in/switch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/tabs/': RouteRecordInfo<
      '/feature/component/built_in/tabs/',
      '/feature/component/built_in/tabs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/timeline/': RouteRecordInfo<
      '/feature/component/built_in/timeline/',
      '/feature/component/built_in/timeline',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/toast/': RouteRecordInfo<
      '/feature/component/built_in/toast/',
      '/feature/component/built_in/toast',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/built_in/trend/': RouteRecordInfo<
      '/feature/component/built_in/trend/',
      '/feature/component/built_in/trend',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/component/composite': RouteRecordInfo<
      '/feature/component/composite',
      '/feature/component/composite',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/function/errorLog': RouteRecordInfo<
      '/feature/function/errorLog',
      '/feature/function/errorLog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/function/font': RouteRecordInfo<
      '/feature/function/font',
      '/feature/function/font',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/function/i18n': RouteRecordInfo<
      '/feature/function/i18n',
      '/feature/function/i18n',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/function/icon': RouteRecordInfo<
      '/feature/function/icon',
      '/feature/function/icon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/function/keepAlive': RouteRecordInfo<
      '/feature/function/keepAlive',
      '/feature/function/keepAlive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/function/scroll': RouteRecordInfo<
      '/feature/function/scroll',
      '/feature/function/scroll',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/function/scroll2': RouteRecordInfo<
      '/feature/function/scroll2',
      '/feature/function/scroll2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/function/title': RouteRecordInfo<
      '/feature/function/title',
      '/feature/function/title',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/function/unocss': RouteRecordInfo<
      '/feature/function/unocss',
      '/feature/function/unocss',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/function/watermark': RouteRecordInfo<
      '/feature/function/watermark',
      '/feature/function/watermark',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/function/zoomable': RouteRecordInfo<
      '/feature/function/zoomable',
      '/feature/function/zoomable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/navbar/custom-area': RouteRecordInfo<
      '/feature/navbar/custom-area',
      '/feature/navbar/custom-area',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/navbar/custom-navbar': RouteRecordInfo<
      '/feature/navbar/custom-navbar',
      '/feature/navbar/custom-navbar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/navbar/custom-title': RouteRecordInfo<
      '/feature/navbar/custom-title',
      '/feature/navbar/custom-title',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/navbar/default': RouteRecordInfo<
      '/feature/navbar/default',
      '/feature/navbar/default',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/navbar/extra': RouteRecordInfo<
      '/feature/navbar/extra',
      '/feature/navbar/extra',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/navbar/mode': RouteRecordInfo<
      '/feature/navbar/mode',
      '/feature/navbar/mode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/navbar/none': RouteRecordInfo<
      '/feature/navbar/none',
      '/feature/navbar/none',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/navbar/preset': RouteRecordInfo<
      '/feature/navbar/preset',
      '/feature/navbar/preset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/navbar/style': RouteRecordInfo<
      '/feature/navbar/style',
      '/feature/navbar/style',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/navbar/title-no-center': RouteRecordInfo<
      '/feature/navbar/title-no-center',
      '/feature/navbar/title-no-center',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/page/loadmore': RouteRecordInfo<
      '/feature/page/loadmore',
      '/feature/page/loadmore',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/page/productlist': RouteRecordInfo<
      '/feature/page/productlist',
      '/feature/page/productlist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/page/schedule': RouteRecordInfo<
      '/feature/page/schedule',
      '/feature/page/schedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/permission/': RouteRecordInfo<
      '/feature/permission/',
      '/feature/permission',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/permission/test': RouteRecordInfo<
      '/feature/permission/test',
      '/feature/permission/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/plugin/animation': RouteRecordInfo<
      '/feature/plugin/animation',
      '/feature/plugin/animation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/plugin/echarts': RouteRecordInfo<
      '/feature/plugin/echarts',
      '/feature/plugin/echarts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/plugin/esign': RouteRecordInfo<
      '/feature/plugin/esign',
      '/feature/plugin/esign',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/plugin/qrcode': RouteRecordInfo<
      '/feature/plugin/qrcode',
      '/feature/plugin/qrcode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/plugin/swiper': RouteRecordInfo<
      '/feature/plugin/swiper',
      '/feature/plugin/swiper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/plugin/vchart': RouteRecordInfo<
      '/feature/plugin/vchart',
      '/feature/plugin/vchart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/tabbar/badge': RouteRecordInfo<
      '/feature/tabbar/badge',
      '/feature/tabbar/badge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/tabbar/custom-area': RouteRecordInfo<
      '/feature/tabbar/custom-area',
      '/feature/tabbar/custom-area',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/tabbar/default': RouteRecordInfo<
      '/feature/tabbar/default',
      '/feature/tabbar/default',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/tabbar/extra': RouteRecordInfo<
      '/feature/tabbar/extra',
      '/feature/tabbar/extra',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/tabbar/mode': RouteRecordInfo<
      '/feature/tabbar/mode',
      '/feature/tabbar/mode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/tabbar/multi': RouteRecordInfo<
      '/feature/tabbar/multi',
      '/feature/tabbar/multi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/feature/tabbar/style': RouteRecordInfo<
      '/feature/tabbar/style',
      '/feature/tabbar/style',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'reload': RouteRecordInfo<
      'reload',
      '/reload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/': RouteRecordInfo<
      '/user/',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/views/feature/index.vue': {
      routes:
        | '/feature/'
      views:
        | never
    }
    'src/views/feature/component/basic.vue': {
      routes:
        | '/feature/component/basic'
      views:
        | never
    }
    'src/views/feature/component/built_in/animated_count_to/index.vue': {
      routes:
        | '/feature/component/built_in/animated_count_to/'
      views:
        | never
    }
    'src/views/feature/component/built_in/avatar/index.vue': {
      routes:
        | '/feature/component/built_in/avatar/'
      views:
        | never
    }
    'src/views/feature/component/built_in/badge/index.vue': {
      routes:
        | '/feature/component/built_in/badge/'
      views:
        | never
    }
    'src/views/feature/component/built_in/button/index.vue': {
      routes:
        | '/feature/component/built_in/button/'
      views:
        | never
    }
    'src/views/feature/component/built_in/card/index.vue': {
      routes:
        | '/feature/component/built_in/card/'
      views:
        | never
    }
    'src/views/feature/component/built_in/checkbox/index.vue': {
      routes:
        | '/feature/component/built_in/checkbox/'
      views:
        | never
    }
    'src/views/feature/component/built_in/count_to/index.vue': {
      routes:
        | '/feature/component/built_in/count_to/'
      views:
        | never
    }
    'src/views/feature/component/built_in/digital_card/index.vue': {
      routes:
        | '/feature/component/built_in/digital_card/'
      views:
        | never
    }
    'src/views/feature/component/built_in/divider/index.vue': {
      routes:
        | '/feature/component/built_in/divider/'
      views:
        | never
    }
    'src/views/feature/component/built_in/drawer/index.vue': {
      routes:
        | '/feature/component/built_in/drawer/'
      views:
        | never
    }
    'src/views/feature/component/built_in/input/index.vue': {
      routes:
        | '/feature/component/built_in/input/'
      views:
        | never
    }
    'src/views/feature/component/built_in/loading/index.vue': {
      routes:
        | '/feature/component/built_in/loading/'
      views:
        | never
    }
    'src/views/feature/component/built_in/marquee/index.vue': {
      routes:
        | '/feature/component/built_in/marquee/'
      views:
        | never
    }
    'src/views/feature/component/built_in/modal/index.vue': {
      routes:
        | '/feature/component/built_in/modal/'
      views:
        | never
    }
    'src/views/feature/component/built_in/multi_step_loader/index.vue': {
      routes:
        | '/feature/component/built_in/multi_step_loader/'
      views:
        | never
    }
    'src/views/feature/component/built_in/page_main/index.vue': {
      routes:
        | '/feature/component/built_in/page_main/'
      views:
        | never
    }
    'src/views/feature/component/built_in/particles_bg/index.vue': {
      routes:
        | '/feature/component/built_in/particles_bg/'
      views:
        | never
    }
    'src/views/feature/component/built_in/pattern_bg/index.vue': {
      routes:
        | '/feature/component/built_in/pattern_bg/'
      views:
        | never
    }
    'src/views/feature/component/built_in/scratch_off/index.vue': {
      routes:
        | '/feature/component/built_in/scratch_off/'
      views:
        | never
    }
    'src/views/feature/component/built_in/scroll_area/index.vue': {
      routes:
        | '/feature/component/built_in/scroll_area/'
      views:
        | never
    }
    'src/views/feature/component/built_in/select/index.vue': {
      routes:
        | '/feature/component/built_in/select/'
      views:
        | never
    }
    'src/views/feature/component/built_in/slider/index.vue': {
      routes:
        | '/feature/component/built_in/slider/'
      views:
        | never
    }
    'src/views/feature/component/built_in/sparkline/index.vue': {
      routes:
        | '/feature/component/built_in/sparkline/'
      views:
        | never
    }
    'src/views/feature/component/built_in/spring_drawer/index.vue': {
      routes:
        | '/feature/component/built_in/spring_drawer/'
      views:
        | never
    }
    'src/views/feature/component/built_in/switch/index.vue': {
      routes:
        | '/feature/component/built_in/switch/'
      views:
        | never
    }
    'src/views/feature/component/built_in/tabs/index.vue': {
      routes:
        | '/feature/component/built_in/tabs/'
      views:
        | never
    }
    'src/views/feature/component/built_in/timeline/index.vue': {
      routes:
        | '/feature/component/built_in/timeline/'
      views:
        | never
    }
    'src/views/feature/component/built_in/toast/index.vue': {
      routes:
        | '/feature/component/built_in/toast/'
      views:
        | never
    }
    'src/views/feature/component/built_in/trend/index.vue': {
      routes:
        | '/feature/component/built_in/trend/'
      views:
        | never
    }
    'src/views/feature/component/composite.vue': {
      routes:
        | '/feature/component/composite'
      views:
        | never
    }
    'src/views/feature/function/errorLog.vue': {
      routes:
        | '/feature/function/errorLog'
      views:
        | never
    }
    'src/views/feature/function/font.vue': {
      routes:
        | '/feature/function/font'
      views:
        | never
    }
    'src/views/feature/function/i18n.vue': {
      routes:
        | '/feature/function/i18n'
      views:
        | never
    }
    'src/views/feature/function/icon.vue': {
      routes:
        | '/feature/function/icon'
      views:
        | never
    }
    'src/views/feature/function/keepAlive.vue': {
      routes:
        | '/feature/function/keepAlive'
      views:
        | never
    }
    'src/views/feature/function/scroll.vue': {
      routes:
        | '/feature/function/scroll'
      views:
        | never
    }
    'src/views/feature/function/scroll2.vue': {
      routes:
        | '/feature/function/scroll2'
      views:
        | never
    }
    'src/views/feature/function/title.vue': {
      routes:
        | '/feature/function/title'
      views:
        | never
    }
    'src/views/feature/function/unocss.vue': {
      routes:
        | '/feature/function/unocss'
      views:
        | never
    }
    'src/views/feature/function/watermark.vue': {
      routes:
        | '/feature/function/watermark'
      views:
        | never
    }
    'src/views/feature/function/zoomable.vue': {
      routes:
        | '/feature/function/zoomable'
      views:
        | never
    }
    'src/views/feature/navbar/custom-area.vue': {
      routes:
        | '/feature/navbar/custom-area'
      views:
        | never
    }
    'src/views/feature/navbar/custom-navbar.vue': {
      routes:
        | '/feature/navbar/custom-navbar'
      views:
        | never
    }
    'src/views/feature/navbar/custom-title.vue': {
      routes:
        | '/feature/navbar/custom-title'
      views:
        | never
    }
    'src/views/feature/navbar/default.vue': {
      routes:
        | '/feature/navbar/default'
      views:
        | never
    }
    'src/views/feature/navbar/extra.vue': {
      routes:
        | '/feature/navbar/extra'
      views:
        | never
    }
    'src/views/feature/navbar/mode.vue': {
      routes:
        | '/feature/navbar/mode'
      views:
        | never
    }
    'src/views/feature/navbar/none.vue': {
      routes:
        | '/feature/navbar/none'
      views:
        | never
    }
    'src/views/feature/navbar/preset.vue': {
      routes:
        | '/feature/navbar/preset'
      views:
        | never
    }
    'src/views/feature/navbar/style.vue': {
      routes:
        | '/feature/navbar/style'
      views:
        | never
    }
    'src/views/feature/navbar/title-no-center.vue': {
      routes:
        | '/feature/navbar/title-no-center'
      views:
        | never
    }
    'src/views/feature/page/loadmore.vue': {
      routes:
        | '/feature/page/loadmore'
      views:
        | never
    }
    'src/views/feature/page/productlist.vue': {
      routes:
        | '/feature/page/productlist'
      views:
        | never
    }
    'src/views/feature/page/schedule.vue': {
      routes:
        | '/feature/page/schedule'
      views:
        | never
    }
    'src/views/feature/permission/index.vue': {
      routes:
        | '/feature/permission/'
      views:
        | never
    }
    'src/views/feature/permission/test.vue': {
      routes:
        | '/feature/permission/test'
      views:
        | never
    }
    'src/views/feature/plugin/animation.vue': {
      routes:
        | '/feature/plugin/animation'
      views:
        | never
    }
    'src/views/feature/plugin/echarts.vue': {
      routes:
        | '/feature/plugin/echarts'
      views:
        | never
    }
    'src/views/feature/plugin/esign.vue': {
      routes:
        | '/feature/plugin/esign'
      views:
        | never
    }
    'src/views/feature/plugin/qrcode.vue': {
      routes:
        | '/feature/plugin/qrcode'
      views:
        | never
    }
    'src/views/feature/plugin/swiper.vue': {
      routes:
        | '/feature/plugin/swiper'
      views:
        | never
    }
    'src/views/feature/plugin/vchart.vue': {
      routes:
        | '/feature/plugin/vchart'
      views:
        | never
    }
    'src/views/feature/tabbar/badge.vue': {
      routes:
        | '/feature/tabbar/badge'
      views:
        | never
    }
    'src/views/feature/tabbar/custom-area.vue': {
      routes:
        | '/feature/tabbar/custom-area'
      views:
        | never
    }
    'src/views/feature/tabbar/default.vue': {
      routes:
        | '/feature/tabbar/default'
      views:
        | never
    }
    'src/views/feature/tabbar/extra.vue': {
      routes:
        | '/feature/tabbar/extra'
      views:
        | never
    }
    'src/views/feature/tabbar/mode.vue': {
      routes:
        | '/feature/tabbar/mode'
      views:
        | never
    }
    'src/views/feature/tabbar/multi.vue': {
      routes:
        | '/feature/tabbar/multi'
      views:
        | never
    }
    'src/views/feature/tabbar/style.vue': {
      routes:
        | '/feature/tabbar/style'
      views:
        | never
    }
    'src/views/login.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'src/views/reload.vue': {
      routes:
        | 'reload'
      views:
        | never
    }
    'src/views/user/index.vue': {
      routes:
        | '/user/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
